// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlympicGames.Models;

namespace OlympicGames.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameID");

                    b.HasIndex("SportID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "aus",
                            CountryImage = "Austria.PNG",
                            GameID = "par",
                            Name = "Austria",
                            SportID = "cou"
                        },
                        new
                        {
                            CountryID = "bra",
                            CountryImage = "Brazil.PNG",
                            GameID = "sum",
                            Name = "Brazil",
                            SportID = "rou"
                        },
                        new
                        {
                            CountryID = "can",
                            CountryImage = "Canada.PNG",
                            GameID = "win",
                            Name = "Canada",
                            SportID = "cin"
                        },
                        new
                        {
                            CountryID = "chi",
                            CountryImage = "China.PNG",
                            GameID = "sum",
                            Name = "China",
                            SportID = "din"
                        },
                        new
                        {
                            CountryID = "cyp",
                            CountryImage = "Cyprus.PNG",
                            GameID = "you",
                            Name = "Cyprus",
                            SportID = "bin"
                        },
                        new
                        {
                            CountryID = "fin",
                            CountryImage = "Finland.PNG",
                            GameID = "par",
                            Name = "Finland",
                            SportID = "cou"
                        },
                        new
                        {
                            CountryID = "fra",
                            CountryImage = "France.PNG",
                            GameID = "you",
                            Name = "France",
                            SportID = "bin"
                        },
                        new
                        {
                            CountryID = "ger",
                            CountryImage = "Germany.PNG",
                            GameID = "sum",
                            Name = "Germany",
                            SportID = "din"
                        },
                        new
                        {
                            CountryID = "gre",
                            CountryImage = "GreatBritain.PNG",
                            GameID = "win",
                            Name = "GreatBritain",
                            SportID = "cin"
                        },
                        new
                        {
                            CountryID = "ita",
                            CountryImage = "Italy.PNG",
                            GameID = "win",
                            Name = "Italy",
                            SportID = "bou"
                        },
                        new
                        {
                            CountryID = "jam",
                            CountryImage = "Jamaica.PNG",
                            GameID = "win",
                            Name = "Jamaica",
                            SportID = "bou"
                        },
                        new
                        {
                            CountryID = "jap",
                            CountryImage = "Japan.PNG",
                            GameID = "win",
                            Name = "Japan",
                            SportID = "bou"
                        },
                        new
                        {
                            CountryID = "mex",
                            CountryImage = "Mexico.PNG",
                            GameID = "sum",
                            Name = "Mexico",
                            SportID = "din"
                        },
                        new
                        {
                            CountryID = "net",
                            CountryImage = "Netherlands.PNG",
                            GameID = "sum",
                            Name = "Netherlands",
                            SportID = "rou"
                        },
                        new
                        {
                            CountryID = "pak",
                            CountryImage = "Pakistan.PNG",
                            GameID = "par",
                            Name = "Pakistan",
                            SportID = "cou"
                        },
                        new
                        {
                            CountryID = "por",
                            CountryImage = "Portugal.PNG",
                            GameID = "you",
                            Name = "Portugal",
                            SportID = "sou"
                        },
                        new
                        {
                            CountryID = "rus",
                            CountryImage = "Russia.PNG",
                            GameID = "you",
                            Name = "Russia",
                            SportID = "bin"
                        },
                        new
                        {
                            CountryID = "slo",
                            CountryImage = "Slovakia.PNG",
                            GameID = "you",
                            Name = "Slovakia",
                            SportID = "sou"
                        },
                        new
                        {
                            CountryID = "swe",
                            CountryImage = "Sweden.PNG",
                            GameID = "win",
                            Name = "Sweden",
                            SportID = "cin"
                        },
                        new
                        {
                            CountryID = "tha",
                            CountryImage = "Thailand.PNG",
                            GameID = "par",
                            Name = "Thailand",
                            SportID = "ain"
                        },
                        new
                        {
                            CountryID = "ukr",
                            CountryImage = "Ukraine.PNG",
                            GameID = "par",
                            Name = "Ukraine",
                            SportID = "ain"
                        },
                        new
                        {
                            CountryID = "ura",
                            CountryImage = "Uraguay.PNG",
                            GameID = "par",
                            Name = "Uraguay",
                            SportID = "ain"
                        },
                        new
                        {
                            CountryID = "usa",
                            CountryImage = "USA.PNG",
                            GameID = "sum",
                            Name = "USA",
                            SportID = "rou"
                        },
                        new
                        {
                            CountryID = "zim",
                            CountryImage = "Zimbabwe.PNG",
                            GameID = "par",
                            Name = "Zimbabwe",
                            SportID = "cou"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "win",
                            GName = "Winter Olympics"
                        },
                        new
                        {
                            GameID = "sum",
                            GName = "Summer Olympics"
                        },
                        new
                        {
                            GameID = "par",
                            GName = "Paralympics"
                        },
                        new
                        {
                            GameID = "you",
                            GName = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Sport", b =>
                {
                    b.Property<string>("SportID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SportName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            SportID = "cin",
                            SportName = "Curling",
                            SportType = "Indoor"
                        },
                        new
                        {
                            SportID = "bou",
                            SportName = "Bobsleigh",
                            SportType = "Outdoor"
                        },
                        new
                        {
                            SportID = "din",
                            SportName = "Diving",
                            SportType = "Indoor"
                        },
                        new
                        {
                            SportID = "rou",
                            SportName = "Road Cycling",
                            SportType = "Outdoor"
                        },
                        new
                        {
                            SportID = "ain",
                            SportName = "Archery",
                            SportType = "Indoor"
                        },
                        new
                        {
                            SportID = "cou",
                            SportName = "Canoe Sprint",
                            SportType = "Outdoor"
                        },
                        new
                        {
                            SportID = "bin",
                            SportName = "Breakdancing",
                            SportType = "Indoor"
                        },
                        new
                        {
                            SportID = "sou",
                            SportName = "Skateboarding",
                            SportType = "Outdoor"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.HasOne("OlympicGames.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");

                    b.HasOne("OlympicGames.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportID");
                });
#pragma warning restore 612, 618
        }
    }
}
